name: portfolio_website
description: Portfolio Website Template
publish_to: 'none'

version: 1.6.5+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  simple_animations: ^4.2.0
  font_awesome_flutter: ^10.1.0
  eva_icons_flutter: ^3.1.0
  delayed_display: ^2.0.0
  provider: ^6.0.3
  page_transition: ^2.0.9
  url_launcher: ^6.1.5
  parallax_animation: ^0.0.3
  firebase_core: ^1.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/main_page_placeholder.jpg

  fonts:
    - family: SanFrancisco
      fonts:
        - asset: assets/fonts/san_francisco/SFBlack.otf
          weight: 900
        - asset: assets/fonts/san_francisco/SFHeavy.otf
          weight: 800
        - asset: assets/fonts/san_francisco/SFBold.ttf
          weight: 700
        - asset: assets/fonts/san_francisco/SFSemibold.otf
          weight: 600
        - asset: assets/fonts/san_francisco/SFMedium.otf
          weight: 500
        - asset: assets/fonts/san_francisco/SFRegular.otf
          weight: 400
        - asset: assets/fonts/san_francisco/SFLight.ttf
          weight: 300
#        - asset: assets/fonts/san_francisco/SFThin.otf
#          weight: 200
#        - asset: assets/fonts/san_francisco/SFUltralight.otf
#          weight: 100

    - family: SanFranciscoThin
      fonts:
        - asset: assets/fonts/san_francisco/SFThin.otf
          weight: 100

    - family: SanFranciscoUltraLight
      fonts:
        - asset: assets/fonts/san_francisco/SFUltralight.otf